import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/store/providers";
import SideBar from "./components/SideBar/SideBar.jsx";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `Heros Path`,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          {token && <SideBar />}
          {children}
        </body>
      </Providers>
    </html>
  );
}
