import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/store/providers";
import SideBar from "./components/SideBar/SideBar.jsx";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `Heros Path`,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        />
      </Head>
      <Providers>
        <body className={inter.className}>
          <SideBar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
